config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  devise_scope :user do
    authenticated :user do
      root to: 'categories#index', as: :authenticated_root
    end
    unauthenticated :user do
      root to: 'homes#splash', as: :unauthenticated_root
     
    end
  end

  resources :categories do
    resources :expenses 
  end

  post 'categories/create', to: 'categories#create', as: :categories_create
  post  'categories/:category_id/expenses', to: 'expenses#create', as: :expenses_create
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    return unless user.present?

    can :read, Category, author_id: user.id
    can :manage, Category, author_id: user.id

    can :read, Expense, category: { author_id: user.id }
    can :manage, Expense, category: { author_id: user.id }
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  belongs_to :author, class_name: 'User', foreign_key: 'author_id'

  has_and_belongs_to_many :expenses, join_table: 'expense_categories', dependent: :destroy
  validates :name, :icon, presence: true
end

app/models/expense.rb
class Expense < ApplicationRecord
  belongs_to :author, class_name: 'User', foreign_key: 'author_id'
  has_and_belongs_to_many :categories, join_table: 'expense_categories', dependent: :destroy

  validates :name, presence: true
  validates :amount, presence: true, numericality: { greater_than_or_equal_to: 0 }
end

app/models/expense_category.rb
class ExpenseCategory < ApplicationRecord
  belongs_to :expense
  belongs_to :category
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :categories, foreign_key: 'author_id', dependent: :destroy
  has_many :expenses, foreign_key: 'author_id', dependent: :destroy

  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up) do |user|
      user.permit(:name, :email, :password, :password_confirmation)
    end
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = Category.includes(:author).all
    @user = current_user
    @category = Category.new
  end

  def show
    @user = current_user
    @category = @user.categories.includes(:author, :expenses).find(params[:id])

    render :show
  end

  def new
    @user = current_user
    @category = Category.new
  end

  def create
    @user = current_user
    @category = @user.categories.build(category_param)

    if @category.save
      redirect_to categories_path, notice: 'Category successfully create'
    else
      flash.now[:error] = @category.errors.full_message.to_sentence
      render :new
    end
  end

  def destroy
    @category = current_user.categories.find(params[:id])

    if @category.destroy
      redirect_to categories_path, notice: 'Category was successfully deleted'
    else
      @category.errors.full_messages
    end
  end

  def category_param
    params.require(:category).permit(:name, :icon, :author_id)
  end
end

app/controllers/expenses_controller.rb
class ExpensesController < ApplicationController
  before_action :set_category
  def new
    @user = current_user
    @expense = @category.expenses.new
  end

  def create
    @expense = Expense.new(name: expense_params[:name], amount: expense_params[:amount])
    @expense.author = current_user
    @category = Category.find(expense_params[:category_id])

    if @expense.save
      @category.expenses << @expense
      redirect_to category_path(expense_params[:category_id]), notice: 'Expense was successfully created'
    else
      puts @expense.errors.full_messages
      flash.now[:error] = @expense.errors.full_messages.to_sentence
      render :new
    end
  end

  def destroy
    @category = Category.includes(:author).find(params[:category_id])
    @expense = @category.expenses.find(params[:id])
    if @expense.destroy
      redirect_to category_path(@category), notice: 'Category was successfully deleted'
    else
      @category.errors.full_messages
    end
  end

  private

  def set_category
    @category = Category.includes(:author).find(params[:category_id])
  end

  def expense_params
    params.require(:expense).permit(:name, :amount, :category_id)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:splash]
  def index; end

  def splash; end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/expenses_helper.rb
module ExpensesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/categories/index.html.erb
<% if user_signed_in? %>

<section class='logged_in_user_form'>

  <nav class='navbar'>
    <div class='menu' onclick='toggleMenu()'> menu</div>
    <h1>CATEGORIES</h1>

    <% if user_signed_in? %>
      <%= button_to 'Log Out', destroy_user_session_path, method: :delete, class:'logout' %> 
    <% end %>
  </nav>

  <ul class='page_body'>

  <% if @categories.empty? %>
    <li>
    <%= link_to 'New CATEGORY', new_category_path, class:'add_button' %>
    </li>
  <% end %>

    <% @categories.each do |category| %> 
      <li class='category_cont'>
        <%=render partial: 'partials/category', locals: { category: category, author: @user } %>
      </li>  
      <br> 
    <% end %>
  </ul>

  <div class='add_button_cont'>
    <%= link_to 'New CATEGORY', new_category_path, class:'add_button' %>
  </div>

  <div id='menuContent' class='menu-content'>
  <span class="close-button" onclick="closeMenu()">x</span>
    <%= button_to 'Log Out', destroy_user_session_path, method: :delete, class:'logout' %> 
  </div>
</section>

<script>
function toggleMenu() {
  var menuContent = document.getElementById('menuContent');
    menuContent.style.display = 'block';
}
function closeMenu() {
    var menuContent = document.getElementById('menuContent');
    menuContent.style.display = 'none';
  }


</script>

<% end %>

app/views/categories/new.html.erb
<section class='logged_in_user_form'>

<nav class='navbar'>
    <div>
    <%= link_to 'Back', categories_path %>
    </div>

    <h1>NEW CATEGORY</h1>

    <div>Search</div>
  </nav>

  <%= form_with model: @category, url: categories_create_path, method: :post, local: true, class:'form' do |f| %>
    <%= f.label :name, style: 'display:none' %>
    <%= f.text_field :name, required: true, placeholder:'Name', class:'login_filed' %>
    <hr>
    <br>

    <%= f.label :icon, style: 'display:none' %>
    <%= f.text_field :icon, required: true, placeholder:'Icon/image', class:'login_filed' %>
    <hr>
    <br>
    <%= f.hidden_field :author_id, value: @user.id %>
    <%= f.submit 'Create Category', class:'login_filed' %>
  <% end %> 

</section>

<% if flash[:notice] %>
  <div>
   <%= flash[:notice] %>
  </div>
<% end %>

app/views/categories/show.html.erb
<section class='logged_in_user_form'>
  <nav class='navbar'>
    <div>
      <%= link_to 'Back', categories_path %>
    </div>

    <h1>TRANSACTIONS</h1>

    <div>Search</div>
  </nav>

  <div class='cat_txn_page'>
    <div><%= @category.name %></div>
    <div><%= @category.expenses.sum(:amount) %></div>
 
  </div>
  <ul class='page_body'>
  <% @category.expenses.order(created_at: :desc).each do |expense| %>
    <li class='category_cont'>
    <%= render partial: 'partials/expense', locals: { expense: expense, category: @category } %>
  </li>
<% end %>
</ul>

 <div class='add_txn'>
 <a class='add_txn_link' href="/categories/<%= @category.id %>/expenses/new">Create transaction</a>
 </div>



</section>

app/views/expenses/index.html.erb
<h1>Expenses</h1>

<div>Total: <%= @total_amount %></div>
<%=  %>
<ul>
  <%  @expenses.each do |expense| %>   
    <li>
      <%= render partial: 'partials/expense', locals: { expense:expense } %>
      <% expense.categories.each do |category| %>
        <div>category: </div><%= category.name %>
      <% end %>
    </li>    
  <% end %>
  
</ul>

app/views/expenses/new.html.erb
<section class='logged_in_user_form'>


<nav class='navbar'>
    <div>
    <%= link_to 'Back', category_path(@category) %>
    </div>

    <h1>NEW TRANSACTION</h1>

    <div>Search</div>
  </nav>

  <%= form_with model: @expense, url: category_expenses_path(@category), method: :post, local: true, class:'form' do |f| %>
    <%= f.label :name, style: 'display:none' %>
    <%= f.text_field :name, required: true, placeholder:'Name', class:'login_filed' %>
    <hr>

    <%= f.label :amount, style: 'display:none' %>
    <%= f.text_field :amount, required: true, placeholder:'Amount', class:'login_filed' %>
    <hr>
    <br>

    <%= f.label :category_id %>
    <%= f.select :category_id, current_user.categories.all.map { |category| [category.name, category.id] }, {}, class:'category_select' %>
    <br>
    <br>

    <%= f.submit "Create expense", class:'login_filed' %>
  <% end %>
</section>

app/views/homes/splash.html.erb
<section class='splash'>
  <div class='spalsh_title'>
    <div class='splash_word'><span class='firstl'>E</span>asy Fi<span class='firstl'>nance</span> </div>
  </div>

  <div class=splash_links> 
    <%= link_to 'LOG IN', new_user_session_path, class: 'login' %> 
    <%= link_to 'SIGN UP', new_user_registration_path, class: 'signup' %>
  </div>  
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RorCapstone</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css" rel="stylesheet">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
        <%= yield %>
        <div class="notice"><%= notice %></div>
    <div class="alert"><%= alert %></div>
  </body>
</html>

app/views/partials/_category.html.erb
<% if category.icon.present? %>
<img src="<%= category.icon %>" alt="<%= category.name %>" , class='category_image'>
<% else %>
<p>No image available</p>
<% end %>

<div class='cat_cont2'>
  <div class='cat_cont_det'>
  <a href="/categories/<%= category.id %>">
  <%= category.name %>  
</a>

<div>
  <strong>$<%= category.expenses.sum(:amount) %> </strong>
</div>
  

<% if current_user.present? && can?(:destroy, category) %>
<a href="<%= category_path(category) %>"
data-turbo-method='delete'
data-turbo-confirm='Are you sure?'
data-method='delete'
>REMOVE</a> 
  </div>

  <% end %>

  <div class='cat_time'>
<%= category.created_at.strftime('%d %B %Y') %>
</div>  

</div>

app/views/partials/_expense.html.erb
<div class='expense_partial'>
  <div class='expense_det'>

<div> <%= expense.name %> </div>
<div> <strong>$ <%= expense.amount %> </strong></div>

<% if current_user.present? && can?(:destroy, category) %>
<a href="<%= category_expense_path(@category, expense) %>"
data-turbo-method='delete'
data-turbo-confirm='Are you sure?'
data-method='delete'
>Remove</a>
  </div>
  <% end %>

  <div class='expense_date'>
  <%= expense.created_at.strftime('%d %B %Y') %>
  </div>
</div>
    